import './globals.css';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Navbar from '@/components/nav/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='mx-auto lg:py-10 space-y-10 p-5 lg:p-0'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
